#!/usr/bin/env bash
#Bash script that transferes a file from our client to a server

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
filePath="$1"
serverIp="$2"
scpUserName="$3"
sshPrivateKey="$4"

if [ $# -lt 4 ]; then
       scp -o StrictHostKeyChecking=no "$filePath" "$scpUserName@$serverIp":~/

elif [ -n "$sshPrivateKey" ]; then
	ssh="$ssh -i $sshPrivateKey"
fi

scp "$ssh" "$filePath" "$scpUserName@$serverIp:~/"
