#!/usr/bin/env bash
#Bash script that transferes a file from our client to a server

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
filePath="$1"
serverIp="$2"
scpUserName="$3"
sshPrivateKey="$4"

ssh_option="-o StrictHostKeyChecking=no"

if [ -n "$sshPrivateKey" ]; then
    ssh_option="$ssh_option -i $sshPrivateKey"
fi

scp "$ssh_option" "$filePath" "$scpUserName@$serverIp":~/
