#!/usr/bin/env bash
# Script that install Nginx on my web server

Sudo apt-get update
sudo apt-get -y install nginx
sudo ufw enable
sudo ufw allow 80/tcp
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
