#!/usr/bin/env bash
# 404 not found

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/twitter.com\/FabPaul1 permanent;"
sudo sed -i "s|server_name _;|$redirect|" /etc/nginx/sites-enabled/default

#404 error
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
redirect="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$redirect/" /etc/nginx/sites-enabled/default
sudo service nginx restart
