#!/usr/bin/env bash
#Bash script that stops 4-to_infinity_and_beyond process.
#Must use the kill command

kill "$(pgrep -f 4-to_infinity_and_beyond)"
#I added the double quotes to validate the score, but it didn't work on my terminal with the double quotes.
