#!/usr/bin/env bash
#Bash script that contains content of /etc/passwd using while loop + IFS

#Format: The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO

current_file="/etc/passwd"

while IFS= read -r each_line
do
	f1="$(echo "$each_line" | cut -d ":" -f1)"
	f2="$(echo "$each_line" | cut -d ":" -f2)"
	f3="$(echo "$each_line" | cut -d ":" -f3)"
	f4="$(echo "$each_line" | cut -d ":" -f4)"
	f5="$(echo "$each_line" | cut -d ":" -f5)"
	f6="$(echo "$each_line" | cut -d ":" -f6)"
	f7="$(echo "$each_line" | cut -d ":" -f7)"
	echo "The user ${f1} is part of the ${f4} gang, lives in ${f6} and rides ${f7}. ${f3}'s place is protected by the passcode ${f2}, more info about the user here: ${f5}"

done < "$current_file"
