#!/usr/bin/env bash
#Script that groups visitors IP and HTTP status code from Apache log anddisplays the data in a list format, extracting IP and HTTP from the status code

current_file="apache-access.log"

awk -F' ' '{print $1, $9}' $current_file | sort | uniq -c | sort -rn
