#!/usr/bin/env bash
#Bash script that prints "Best School" from 1-10, printing bad/good luck at 4/8

i=0

while [ $i -lt 10 ]
do
	if [ $i == 3 ]
	then
		echo bad luck
	elif [ $i == 7 ]
	then
		echo good luck
	else
		echo Best School
	fi
	((i++))
done
