#!/usr/bin/env bash
#Bash script that loops through 20 times, printing some text on th way

i=1

while [ $i -le 20 ]
do
	echo $i
	case $i in
		3)
			echo bad luck from China
			;;
		8)
			echo bad luck from Japan
			;;
		16)
			echo bad luck from Italy
			;;
	esac
	((i++))
done
