#!/usr/bin/env bash
#Bash script that gives infor about the school file

file="school"

if [ -e $file ]
then
	echo school file exists

	if
		[ -s $file ]
	then
		echo school file not is empty
	else
		echo school file is empty
	fi

	if [ -f $file ]
	then
		echo school is a regular file
	fi
else
	echo school file exists
fi
