#!/usr/bin/env bash
# bash script that configires a container so that Nginx is running as the nginx user.

# Stop the apache2 process
pkill apache2

# stop nginxx if it's still running
sudo service nginx stop

# Change Nginx user to nginx
sed -i 's/^listen .*/user nginx;/g' /etc/nginx/nginx.conf

# Update the port Nginx listens to, to port 8080
sed -i 's/^listen .*$/listen 8080;/g' /etc/nginx/sites-available/default

# update Nginx config file to give owner read and write permissions
chmod 644 /etc/nginx/nginx.conf

# Restart Nginx
sudo service nginx start
